# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 2
name = "Portfolio"
hasChildren = true

[[main]]
parent = "Portfolio"
name = "All"
url = "/portfolio"
weight = 1

[[main]]
parent = "Portfolio"
name = "VW / HPE: Solution Architecture"
url = "/portfolio/vw-hpe-solution-architecture"
weight = 2

[[main]]
parent = "Portfolio"
name = "Google TimesFM – Opensource contribution"
url = "/portfolio/google-timesfm"
weight = 3

[[main]]
parent = "Portfolio"
name = "Atruvia / Volksbank – Data Warehouse"
url = "/portfolio/atruvia--volksbank-data-warehouse"
weight = 4

[[main]]
parent = "Portfolio"
name = "BMW / HPE: Worldwide backup solution for VMs"
url = "/portfolio/bmw-worldwide-backup-solution"
weight = 5

[[main]]
parent = "Portfolio"
name = "Clinic Buchinger Wilhelmi - Medical Data Warehouse"
url = "/portfolio/clinic-buchinger-wilhelmi-data-warehouse"
weight = 6

[[main]]
parent = "Portfolio"
name = "Vios Investments – Trading Infrastructure"
url = "/portfolio/vios-investments-trading-infrastructure"
weight = 7


[[main]]
weight = 6
name = "Products"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Products"
name = "DocumentChat"
pre = "<i class='dropdown-icon fas fa-users'></i>"
post = "<small class='dropdown-subtitle'>AI SaaS application to allow users to chat with their emails and documents</small>"
url = "/products/DocumentChat"
weight = 1

[[main]]
parent = "Products"
name = "Myopiagraph"
pre = "<i class='dropdown-icon fas fa-eye'></i>"
post = "<small class='dropdown-subtitle'>Myopiagraph is a healthcare software for Myopia management</small>"
url = "/products/myopiagraph"
weight = 2

[[main]]
parent = "Products"
name = "AI Investing Bots"
pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
post = "<small class='dropdown-subtitle'>AI Investing Bots is a website publishing our trade ideas and investment strategies.</small>"
url = "/products/aiinvestingbots"
weight = 4

[[main]]
parent = "Products"
name = "View All Products"
pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
url = "/products"
weight = 5

[[main]]
weight = 13
name = "Blog"
url = "/blog"

[[main]]
weight = 15
name = "About"
hasChildren = true

[[main]]
parent = "About"
name = "FAQ"
url = "/about/faq"
weight = 1

[[main]]
parent = "About"
name = "Imprint"
url = "/about/imprint"
weight = 2

[[main]]
parent = "About"
name = "Privacy Policy"
url = "/about/privacy-policy"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 30

# footer menu left
[[footer_left]]
name = "Privacy Policy"
url = "/about/privacy-policy"
weight = 1

[[footer_left]]
name = "Contact"
url = "/contact"
weight = 2

[[footer_left]]
name = "Imprint"
url = "/about/imprint"
weight = 3

[[footer_left]]
name = "FAQ"
url = "/about/faq"
weight = 4


# footer menu middle
[[footer_middle]]
name = "DocumentChat"
url = "/products/DocumentChat"
weight = 1

[[footer_middle]]
name = "Myopiagraph"
url = "/products/myopiagraph"
weight = 2

[[footer_middle]]
name = "AI Investing Bots"
url = "/products/aiinvestingbots"
weight = 4

# footer menu right
[[footer_right]]
name = "VW / HPE: Solution Architecture"
url = "/portfolio/vw-hpe-solution-architecture"
weight = 2

[[footer_right]]
name = "Google TimesFM – Opensource contribution"
url = "/portfolio/google-timesfm"
weight = 3

[[footer_right]]
name = "Atruvia / Volksbank – Data Warehouse"
url = "/portfolio/atruvia--volksbank-data-warehouse"
weight = 4

[[footer_right]]
name = "BMW / HPE: Worldwide backup solution for VMs"
url = "/portfolio/bmw-worldwide-backup-solution"
weight = 5