# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 2
name = "Portfolio"
hasChildren = true

[[main]]
parent = "Portfolio"
name = "All"
url = "/portfolio"
weight = 1

[[main]]
parent = "Portfolio"
name = "VW / HPE: Solution Architecture"
url = "/portfolio/vw-hpe-solution-architecture"
weight = 2

[[main]]
parent = "Portfolio"
name = "Google TimesFM – Opensource contribution"
url = "/portfolio/google-timesfm"
weight = 3

[[main]]
parent = "Portfolio"
name = "Atruvia / Sparkasse / Volksbank – Data Warehouse"
url = "/portfolio/atruvia-sparkasse-volksbank-data-warehouse"
weight = 4

[[main]]
parent = "Portfolio"
name = "BMW / HPE: Worldwide backup solution for VMs"
url = "/portfolio/bmw-worldwide-backup-solution"
weight = 5

[[main]]
parent = "Portfolio"
name = "Clinic Buchinger Wilhelmi - Medical Data Warehouse"
url = "/portfolio/clinic-buchinger-wilhelmi-data-warehouse"
weight = 6

[[main]]
parent = "Portfolio"
name = "Vios Investments – Trading Infrastructure"
url = "/portfolio/vios-investments-trading-infrastructure"
weight = 7


[[main]]
weight = 6
name = "Produkte"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Produkte"
name = "DokuChat"
pre = "<i class='dropdown-icon fas fa-users'></i>"
post = "<small class='dropdown-subtitle'>KI SaaS-Anwendung, die es Benutzern ermöglicht, mit ihren E-Mails und Dokumenten zu chatten</small>"
url = "/products/dokuchat"
weight = 1

[[main]]
parent = "Produkte"
name = "Myopiagraph"
pre = "<i class='dropdown-icon fas fa-eye'></i>"
post = "<small class='dropdown-subtitle'>Myopiagraph ist eine Gesundheitssoftware für das Myopie-Management</small>"
url = "/products/myopiagraph"
weight = 2

[[main]]
parent = "Produkte"
name = "AI Investing Bots"
pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
post = "<small class='dropdown-subtitle'>AI Investing Bots ist eine Website, die unsere Handelsideen und Anlagestrategien veröffentlicht.</small>"
url = "/products/aiinvestingbots"
weight = 4

[[main]]
parent = "Produkte"
name = "Alle Produkte anzeigen"
pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
url = "/Produkte"
weight = 5

[[main]]
weight = 13
name = "Blog"
url = "/blog"

[[main]]
weight = 15
name = "Über uns"
hasChildren = true

[[main]]
parent = "Über uns"
name = "FAQ"
url = "/about/faq"
weight = 1

[[main]]
parent = "Über uns"
name = "Impressum"
url = "/about/imprint"
weight = 2

[[main]]
parent = "Über uns"
name = "Datenschutzerklärung"
url = "/about/privacy-policy"
weight = 3

[[main]]
name = "Kontakt"
url = "/contact"
weight = 30

# footer menu left
[[footer_left]]
name = "Über uns"
url = "/Über uns"
weight = 1

[[footer_left]]
name = "Team"
url = "/team"
weight = 2

[[footer_left]]
name = "How It Works"
url = "/how-it-works"
weight = 3

[[footer_left]]
name = "Career"
url = "/career"
weight = 4


# footer menu middle
[[footer_middle]]
name = "CRM"
url = "/products/product-1"
weight = 1

[[footer_middle]]
name = "Help Desk"
url = "/products/product-2"
weight = 2

[[footer_middle]]
name = "Workplace"
url = "/products/product-3"
weight = 3

[[footer_middle]]
name = "Analytics"
url = "/products/product-4"
weight = 4

# footer menu right
[[footer_right]]
name = "FAQ"
url = "/faq"
weight = 1

[[footer_right]]
name = "Contact"
url = "/contact"
weight = 2

[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer_right]]
name = "Terms & Conditions"
url = "/terms-conditions"
weight = 4
