# main menu
[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
weight = 2
name = "作品集"
hasChildren = true

[[main]]
parent = "作品集"
name = "全部"
url = "/portfolio"
weight = 1

[[main]]
parent = "作品集"
name = "大众 / HPE: 解决方案架构"
url = "/portfolio/vw-hpe-solution-architecture"
weight = 2

[[main]]
parent = "作品集"
name = "谷歌 TimesFM – 开源贡献"
url = "/portfolio/google-timesfm"
weight = 3

[[main]]
parent = "作品集"
name = "Atruvia / Volksbank – 数据仓库"
url = "/portfolio/atruvia--volksbank-data-warehouse"
weight = 4

[[main]]
parent = "作品集"
name = "宝马 / HPE: 全球虚拟机备份解决方案"
url = "/portfolio/bmw-worldwide-backup-solution"
weight = 5

[[main]]
parent = "作品集"
name = "布兴格威尔赫尔米诊所 - 医疗数据仓库"
url = "/portfolio/clinic-buchinger-wilhelmi-data-warehouse"
weight = 6

[[main]]
parent = "作品集"
name = "Vios 投资 – 交易基础设施"
url = "/portfolio/vios-investments-trading-infrastructure"
weight = 7

[[main]]
weight = 6
name = "产品"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "产品"
name = "DokuChat"
pre = "<i class='dropdown-icon fas fa-users'></i>"
post = "<small class='dropdown-subtitle'>AI SaaS 应用程序，允许用户与他们的电子邮件和文档聊天</small>"
url = "/products/dokuchat"
weight = 1

[[main]]
parent = "产品"
name = "Myopiagraph"
pre = "<i class='dropdown-icon fas fa-eye'></i>"
post = "<small class='dropdown-subtitle'>Myopiagraph 是用于近视管理的医疗软件</small>"
url = "/products/myopiagraph"
weight = 2

[[main]]
parent = "产品"
name = "AI 投资机器人"
pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
post = "<small class='dropdown-subtitle'>AI 投资机器人是一个发布我们的交易想法和投资策略的网站。</small>"
url = "/products/aiinvestingbots"
weight = 4

[[main]]
parent = "产品"
name = "查看所有产品"
pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
url = "/products"
weight = 5

[[main]]
weight = 13
name = "博客"
url = "/blog"

[[main]]
weight = 15
name = "关于"
hasChildren = true

[[main]]
parent = "关于"
name = "常见问题"
url = "/about/faq"
weight = 1

[[main]]
parent = "关于"
name = "印记"
url = "/about/imprint"
weight = 2

[[main]]
parent = "关于"
name = "隐私政策"
url = "/about/privacy-policy"
weight = 3

[[main]]
name = "联系"
url = "/contact"
weight = 30

# footer menu left
[[footer_left]]
name = "隐私政策"
url = "/about/privacy-policy"
weight = 1

[[footer_left]]
name = "联系"
url = "/contact"
weight = 2

[[footer_left]]
name = "印记"
url = "/about/imprint"
weight = 3

[[footer_left]]
name = "常见问题"
url = "/about/faq"
weight = 4

# footer menu middle
[[footer_middle]]
name = "DokuChat"
url = "/products/dokuchat"
weight = 1

[[footer_middle]]
name = "Myopiagraph"
url = "/products/myopiagraph"
weight = 2

[[footer_middle]]
name = "AI 投资机器人"
url = "/products/aiinvestingbots"
weight = 4

# footer menu right
[[footer_right]]
name = "大众 / HPE: 解决方案架构"
url = "/portfolio/vw-hpe-solution-architecture"
weight = 2

[[footer_right]]
name = "谷歌 TimesFM – 开源贡献"
url = "/portfolio/google-timesfm"
weight = 3

[[footer_right]]
name = "Atruvia / Volksbank – 数据仓库"
url = "/portfolio/atruvia--volksbank-data-warehouse"
weight = 4

[[footer_right]]
name = "宝马 / HPE: 全球虚拟机备份解决方案"
url = "/portfolio/bmw-worldwide-backup-solution"
weight = 5
